### ISSUE TITLE
Generate protobuf stub mocks for GrpcClient tests

### ISSUE THREAD

**Issue by ZacharyEspiritu** [googleinterns/cloud-kms-oss-tools#57]

**Comment by ZacharyEspiritu** [comment]
Definition of `cc_grpc_library` can be found here: https://github.com/vam-google/grpc/blob/0f7f745864fc0e09b8edd7ce8967cf9c42ee3ec8/bazel/cc_grpc_library.bzl

BUILD:

```starlark
load(
    "@com_google_googleapis_imports//:imports.bzl",
    "cc_grpc_library",
    "cc_proto_library",
)

cc_proto_library(
    name = "kms_cc_proto",
    deps = ["@com_google_googleapis//google/cloud/kms/v1:kms_proto"],
)

cc_grpc_library(
    name = "kms_cc_grpc",
    srcs = ["@com_google_googleapis//google/cloud/kms/v1:kms_proto"],
    grpc_only = True,
    deps = [":kms_cc_proto"],
)
```

Output:

```bash
$ bazel build kms_cc_grpc
ERROR: /usr/local/google/home/zesp/kmsengine/src/backing/client/BUILD:112:16: in _generate_cc rule //src/backing/client:_kms_cc_grpc_grpc_codegen: 
Traceback (most recent call last):
	File "/usr/local/google/home/zesp/kmsengine/src/backing/client/BUILD", line 112
		_generate_cc(name = '_kms_cc_grpc_grpc_codegen')
	File "/usr/local/google/home/zesp/.cache/bazel/_bazel_zesp/152d8aa07744222e59d50d6a52d4e0ec/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 59, in generate_cc_impl
		proto_path_to_generated_filename(<2 more arguments>)
	File "/usr/local/google/home/zesp/.cache/bazel/_bazel_zesp/152d8aa07744222e59d50d6a52d4e0ec/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 60, in proto_path_to_generated_filename
		_strip_package_from_path(<2 more arguments>)
	File "/usr/local/google/home/zesp/.cache/bazel/_bazel_zesp/152d8aa07744222e59d50d6a52d4e0ec/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 31, in _strip_package_from_path
		fail(<1 more arguments>)
'external/com_google_googleapis/google/cloud/kms/v1/resources.proto' does not lie within 'src/backing/client'.
ERROR: Analysis of target '//src/backing/client:kms_cc_grpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.144s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by ZacharyEspiritu** [comment]
Seems like this is an existing issue: grpc/grpc#20828
