### ISSUE TITLE
ERR_load_strings fails in test environment

### ISSUE THREAD

**Issue by ZacharyEspiritu** [googleinterns/cloud-kms-oss-tools#72]
Blocking #12.

A segmentation fault occurs in the error string loading utility when gRPC is included as a dependency in the backing layer. It doesn't seem to be a symbol conflict issue, but there might be some startup work that OpenSSL and BoringSSL do on init that share some functions from OpenSSL system headers and this initialization work might be clobbering each other. (Stepping through with GDB shows that there's some `pthread` locks that have been deleted which seems to be the reason for the segfault.)

Interestingly, the segmentation fault only occurs when the "load error strings" function is called in a test case, but it doesn't occur when the engine is dynamically loaded by the OpenSSL CLI. So it might just be something about the test environment that is causing this issue.

**Comment by ZacharyEspiritu** [comment]
For reference, gdb stacktrace where `error_test` crashes due to null pthread lock somewhere in `ERR_load_strings`.

```python
zesp@zesp:~/kmsengine/src/bridge/error$ gdb ../../../bazel-bin/src/bridge/error/error_test
[...]
Reading symbols from ../../../bazel-bin/src/bridge/error/error_test...
(gdb) r
Starting program: /usr/local/google/home/zesp/.cache/bazel/_bazel_zesp/152d8aa07744222e59d50d6a52d4e0ec/execroot/__main__/bazel-out/k8-dbg/bin/src/bridge/error/error_test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running main() from gmock_main.cc
[==========] Running 54 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from ErrorTest
[ RUN      ] ErrorTest.ErrorLibraryCodeInitialized
[       OK ] ErrorTest.ErrorLibraryCodeInitialized (0 ms)
[ RUN      ] ErrorTest.ErrorLibraryCodeConstantBetweenCalls
[       OK ] ErrorTest.ErrorLibraryCodeConstantBetweenCalls (0 ms)
[ RUN      ] ErrorTest.LoadErrorStrings

Program received signal SIGSEGV, Segmentation fault.
__GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
27	pthread_rwlock_wrlock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
#1  0x00007ffff6277669 in CRYPTO_THREAD_write_lock ()
   from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007ffff61eda20 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff61ede33 in ERR_load_strings () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff7c9c6b5 in kmsengine::bridge::LoadErrorStringsIntoOpenSSL ()
    at src/bridge/error/error.cc:30
#5  0x0000555555566448 in kmsengine::bridge::(anonymous namespace)::ErrorTest_LoadErrorStrings_Test::TestBody (this=0x5555555a2230) at src/bridge/error/error_test.cc:116
#6  0x00007ffff645e87d in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x5555555a2230, method=&virtual testing::Test::TestBody(), 
    location=0x7ffff646f3bb "the test body")
    at external/com_google_googletest/googletest/src/gtest.cc:2433
#7  0x00007ffff6459ba3 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x5555555a2230, method=&virtual testing::Test::TestBody(), 
    location=0x7ffff646f3bb "the test body")
    at external/com_google_googletest/googletest/src/gtest.cc:2469
#8  0x00007ffff6443cae in testing::Test::Run (this=0x5555555a2230)
    at external/com_google_googletest/googletest/src/gtest.cc:2508
[...]
```
